name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: print greeting
        run:
          echo "hello world!"
          echo "hai"
      - name: print bye
        run: echo "good bye!"
        
    
